# RBAC for Provisioner - manages CloudNativePG clusters
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner
  namespace: orochi-cloud
  labels:
    app.kubernetes.io/name: orochi-cloud
    app.kubernetes.io/component: provisioner
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: provisioner
  namespace: orochi-cloud
  labels:
    app.kubernetes.io/name: orochi-cloud
    app.kubernetes.io/component: provisioner
rules:
  # CloudNativePG cluster management
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["clusters", "poolers", "scheduledbackups", "backups"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Secrets for database credentials
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # ConfigMaps for cluster configs
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Services for database endpoints
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  # Pods for status checks
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  # Events for debugging
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create"]
  # PVCs for storage management
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: provisioner
  namespace: orochi-cloud
  labels:
    app.kubernetes.io/name: orochi-cloud
    app.kubernetes.io/component: provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: provisioner
subjects:
  - kind: ServiceAccount
    name: provisioner
    namespace: orochi-cloud
