apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: control-plane-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: control-plane
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dashboard-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: dashboard
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: autoscaler-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: autoscaler
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: provisioner-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: provisioner
