/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClustersIndexRouteImport } from './routes/clusters.index'
import { Route as ClustersNewRouteImport } from './routes/clusters.new'
import { Route as ClustersIdRouteImport } from './routes/clusters.$id'
import { Route as ClustersIdSettingsRouteImport } from './routes/clusters.$id.settings'
import { Route as AuthCallbackProviderRouteImport } from './routes/auth.callback.$provider'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersIndexRoute = ClustersIndexRouteImport.update({
  id: '/clusters/',
  path: '/clusters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersNewRoute = ClustersNewRouteImport.update({
  id: '/clusters/new',
  path: '/clusters/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersIdRoute = ClustersIdRouteImport.update({
  id: '/clusters/$id',
  path: '/clusters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersIdSettingsRoute = ClustersIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClustersIdRoute,
} as any)
const AuthCallbackProviderRoute = AuthCallbackProviderRouteImport.update({
  id: '/auth/callback/$provider',
  path: '/auth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/clusters/$id': typeof ClustersIdRouteWithChildren
  '/clusters/new': typeof ClustersNewRoute
  '/clusters': typeof ClustersIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/clusters/$id/settings': typeof ClustersIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/clusters/$id': typeof ClustersIdRouteWithChildren
  '/clusters/new': typeof ClustersNewRoute
  '/clusters': typeof ClustersIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/clusters/$id/settings': typeof ClustersIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/clusters/$id': typeof ClustersIdRouteWithChildren
  '/clusters/new': typeof ClustersNewRoute
  '/clusters/': typeof ClustersIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/clusters/$id/settings': typeof ClustersIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/clusters/$id'
    | '/clusters/new'
    | '/clusters'
    | '/auth/callback/$provider'
    | '/clusters/$id/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/clusters/$id'
    | '/clusters/new'
    | '/clusters'
    | '/auth/callback/$provider'
    | '/clusters/$id/settings'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/clusters/$id'
    | '/clusters/new'
    | '/clusters/'
    | '/auth/callback/$provider'
    | '/clusters/$id/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ClustersIdRoute: typeof ClustersIdRouteWithChildren
  ClustersNewRoute: typeof ClustersNewRoute
  ClustersIndexRoute: typeof ClustersIndexRoute
  AuthCallbackProviderRoute: typeof AuthCallbackProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters/': {
      id: '/clusters/'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters/new': {
      id: '/clusters/new'
      path: '/clusters/new'
      fullPath: '/clusters/new'
      preLoaderRoute: typeof ClustersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters/$id': {
      id: '/clusters/$id'
      path: '/clusters/$id'
      fullPath: '/clusters/$id'
      preLoaderRoute: typeof ClustersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters/$id/settings': {
      id: '/clusters/$id/settings'
      path: '/settings'
      fullPath: '/clusters/$id/settings'
      preLoaderRoute: typeof ClustersIdSettingsRouteImport
      parentRoute: typeof ClustersIdRoute
    }
    '/auth/callback/$provider': {
      id: '/auth/callback/$provider'
      path: '/auth/callback/$provider'
      fullPath: '/auth/callback/$provider'
      preLoaderRoute: typeof AuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClustersIdRouteChildren {
  ClustersIdSettingsRoute: typeof ClustersIdSettingsRoute
}

const ClustersIdRouteChildren: ClustersIdRouteChildren = {
  ClustersIdSettingsRoute: ClustersIdSettingsRoute,
}

const ClustersIdRouteWithChildren = ClustersIdRoute._addFileChildren(
  ClustersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ClustersIdRoute: ClustersIdRouteWithChildren,
  ClustersNewRoute: ClustersNewRoute,
  ClustersIndexRoute: ClustersIndexRoute,
  AuthCallbackProviderRoute: AuthCallbackProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
