apiVersion: v1
kind: Secret
metadata:
  name: pgdog-secrets
  namespace: orochi-cloud
  labels:
    app: pgdog
    app.kubernetes.io/name: pgdog
    app.kubernetes.io/component: connection-pooler
    app.kubernetes.io/part-of: orochi-cloud
type: Opaque
stringData:
  # JWT Configuration for proxy authentication
  JWT_ISSUER: "orochi-cloud"
  JWT_AUDIENCE: "orochi-db"

  # Database credentials for PgDog to connect to PostgreSQL
  # Format: "username":"password" (one per line)
  # These should be scram-sha-256 hashed passwords in production
  userlist.txt: |
    "orochi_app":"SCRAM-SHA-256$4096:CHANGE_THIS_PASSWORD_HASH"
    "orochi_admin":"SCRAM-SHA-256$4096:CHANGE_THIS_PASSWORD_HASH"
    "orochi_readonly":"SCRAM-SHA-256$4096:CHANGE_THIS_PASSWORD_HASH"
    "orochi_analytics":"SCRAM-SHA-256$4096:CHANGE_THIS_PASSWORD_HASH"

  # Database hosts - replace with actual cluster endpoints
  PRIMARY_DB_HOST: "orochi-primary.orochi-cloud.svc.cluster.local"
  REPLICA_1_DB_HOST: "orochi-replica-1.orochi-cloud.svc.cluster.local"
  REPLICA_2_DB_HOST: "orochi-replica-2.orochi-cloud.svc.cluster.local"

  # Admin password for pgdog admin interface
  PGDOG_ADMIN_PASSWORD: "CHANGE_THIS_ADMIN_PASSWORD"

---
apiVersion: v1
kind: Secret
metadata:
  name: pgdog-tls
  namespace: orochi-cloud
  labels:
    app: pgdog
    app.kubernetes.io/name: pgdog
    app.kubernetes.io/component: connection-pooler
    app.kubernetes.io/part-of: orochi-cloud
type: kubernetes.io/tls
stringData:
  # TLS certificate for client connections
  # Replace with actual certificate from cert-manager or manual provisioning
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_ACTUAL_CERTIFICATE
    -----END CERTIFICATE-----

  tls.key: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_ACTUAL_PRIVATE_KEY
    -----END PRIVATE KEY-----

---
apiVersion: v1
kind: Secret
metadata:
  name: pgdog-jwt-key
  namespace: orochi-cloud
  labels:
    app: pgdog
    app.kubernetes.io/name: pgdog
    app.kubernetes.io/component: connection-pooler
    app.kubernetes.io/part-of: orochi-cloud
type: Opaque
stringData:
  # JWT public key for verifying tokens
  # This should match the key used by the control-plane to sign tokens
  jwt-public-key.pem: |
    -----BEGIN PUBLIC KEY-----
    REPLACE_WITH_ACTUAL_JWT_PUBLIC_KEY
    -----END PUBLIC KEY-----
