apiVersion: v1
kind: Secret
metadata:
  name: pgdog-secrets
  namespace: orochi-cloud
  labels:
    app: pgdog
    app.kubernetes.io/name: pgdog
    app.kubernetes.io/component: connection-pooler
    app.kubernetes.io/part-of: orochi-cloud
type: Opaque
stringData:
  # JWT Configuration for proxy authentication
  JWT_ISSUER: "orochi-cloud"
  JWT_AUDIENCE: "orochi-db"

  # HMAC secret for JWT validation (must match control-plane JWT_SECRET)
  # IMPORTANT: Replace with your actual JWT secret before deploying
  jwt-hmac-secret: "REPLACE_WITH_CONTROL_PLANE_JWT_SECRET"

  # Database credentials for PgDog client authentication
  # Generated via: infrastructure/digitalocean/pgdog/deploy-secrets.sh
  # IMPORTANT: Replace with actual SCRAM-SHA-256 hashes before deploying
  userlist.txt: |
    "orochi_app":"SCRAM-SHA-256$4096:GENERATE_VIA_DEPLOY_SCRIPT"
    "orochi_admin":"SCRAM-SHA-256$4096:GENERATE_VIA_DEPLOY_SCRIPT"
    "orochi_readonly":"SCRAM-SHA-256$4096:GENERATE_VIA_DEPLOY_SCRIPT"
    "orochi_analytics":"SCRAM-SHA-256$4096:GENERATE_VIA_DEPLOY_SCRIPT"

  # Database hosts - replace with actual cluster endpoints
  PRIMARY_DB_HOST: "REPLACE_WITH_PRIMARY_HOST"
  REPLICA_1_DB_HOST: "REPLACE_WITH_REPLICA_1_HOST"
  REPLICA_2_DB_HOST: "REPLACE_WITH_REPLICA_2_HOST"

  # Admin password for pgdog admin interface
  PGDOG_ADMIN_PASSWORD: "REPLACE_WITH_ADMIN_PASSWORD"

---
apiVersion: v1
kind: Secret
metadata:
  name: pgdog-tls
  namespace: orochi-cloud
  labels:
    app: pgdog
    app.kubernetes.io/name: pgdog
    app.kubernetes.io/component: connection-pooler
    app.kubernetes.io/part-of: orochi-cloud
type: kubernetes.io/tls
stringData:
  # TLS certificate for client connections
  # Generated via: infrastructure/digitalocean/pgdog/deploy-secrets.sh
  # Or replace with cert-manager issued certificate
  tls.crt: "REPLACE_VIA_DEPLOY_SCRIPT"
  tls.key: "REPLACE_VIA_DEPLOY_SCRIPT"
