name: howlerops-control-plane
region: sfo
services:
  - name: control-plane
    image:
      registry_type: DOCR
      repository: control-plane
      tag: latest
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    routes:
      - path: /
    envs:
      - key: SERVER_HOST
        value: "0.0.0.0"
      - key: SERVER_PORT
        value: "8080"
      - key: GRPC_HOST
        value: "0.0.0.0"
      - key: GRPC_PORT
        value: "9090"
      - key: JWT_ISSUER
        value: "howlerops"
      - key: DB_SSL_MODE
        value: "require"
      - key: DATABASE_URL
        type: SECRET
        value: "postgresql://doadmin:AVNS_T814ltRhZihG3uSeQFt@orochi-metadata-do-user-32140747-0.e.db.ondigitalocean.com:25060/orochi_control_plane?sslmode=require"
      - key: JWT_SECRET
        type: SECRET
        value: "orochi-jwt-secret-change-in-production-2026"
      - key: ALLOWED_ORIGINS
        value: "https://dashboard.howlerops.com,https://howlerops.com,http://localhost:3000,http://localhost:5173"
      - key: ENCRYPTION_KEY
        type: SECRET
        value: "YEvI5U/r/Us1NtjTy1cuMNXV1+rRvp20"
