apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane
  namespace: orochi-cloud
  labels:
    app: control-plane
    app.kubernetes.io/name: control-plane
    app.kubernetes.io/part-of: orochi-cloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: control-plane
  template:
    metadata:
      labels:
        app: control-plane
    spec:
      containers:
        - name: control-plane
          image: registry.digitalocean.com/orochi-registry/control-plane:latest
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: grpc
          env:
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "8080"
            - name: GRPC_HOST
              value: "0.0.0.0"
            - name: GRPC_PORT
              value: "9090"
            # Database configuration
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: control-plane-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: control-plane-secrets
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: control-plane-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: control-plane-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: control-plane-secrets
                  key: DB_NAME
            - name: DB_SSL_MODE
              valueFrom:
                secretKeyRef:
                  name: control-plane-secrets
                  key: DB_SSL_MODE
            # JWT configuration
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: control-plane-secrets
                  key: JWT_SECRET
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: control-plane-secrets
                  key: JWT_ISSUER
            - name: JWT_ACCESS_TOKEN_TTL
              valueFrom:
                secretKeyRef:
                  name: control-plane-secrets
                  key: JWT_ACCESS_TOKEN_TTL
            - name: JWT_REFRESH_TOKEN_TTL
              valueFrom:
                secretKeyRef:
                  name: control-plane-secrets
                  key: JWT_REFRESH_TOKEN_TTL
            # Admin seeding
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: control-plane-secrets
                  key: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: control-plane-secrets
                  key: ADMIN_PASSWORD
            - name: ADMIN_NAME
              valueFrom:
                secretKeyRef:
                  name: control-plane-secrets
                  key: ADMIN_NAME
            # CORS
            - name: ALLOWED_ORIGINS
              value: "https://dashboard.orochi.cloud,https://orochi-dashboard.fly.dev,http://localhost:3000,http://localhost:5173"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: registry-orochi-registry
---
apiVersion: v1
kind: Service
metadata:
  name: control-plane
  namespace: orochi-cloud
  labels:
    app: control-plane
spec:
  selector:
    app: control-plane
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9090
      targetPort: 9090
