apiVersion: apps/v1
kind: Deployment
metadata:
  name: provisioner
  namespace: orochi-cloud
  labels:
    app: provisioner
    app.kubernetes.io/name: provisioner
    app.kubernetes.io/part-of: orochi-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provisioner
  template:
    metadata:
      labels:
        app: provisioner
    spec:
      serviceAccountName: provisioner
      containers:
        - name: provisioner
          image: registry.digitalocean.com/orochi-registry/provisioner:latest
          ports:
            - containerPort: 8080
              name: grpc
            - containerPort: 9090
              name: metrics
          env:
            - name: GRPC_PORT
              value: "8080"
            - name: METRICS_PORT
              value: "9090"
            - name: LOG_LEVEL
              value: "info"
            - name: DEFAULT_NAMESPACE
              value: "orochi-clusters"
            - name: STORAGE_CLASS
              value: "do-block-storage"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: registry-orochi-registry
---
apiVersion: v1
kind: Service
metadata:
  name: provisioner
  namespace: orochi-cloud
  labels:
    app: provisioner
spec:
  selector:
    app: provisioner
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 9090
      targetPort: 9090
