apiVersion: v1
kind: Secret
metadata:
  name: control-plane-secrets
  namespace: orochi-cloud
type: Opaque
stringData:
  # Database connection
  DB_HOST: "orochi-metadata-do-user-32140747-0.e.db.ondigitalocean.com"
  DB_PORT: "25060"
  DB_USER: "doadmin"
  DB_PASSWORD: "AVNS_T814ltRhZihG3uSeQFt"
  DB_NAME: "orochi_cloud"
  DB_SSL_MODE: "require"

  # JWT Configuration
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production-min-32-chars"
  JWT_ISSUER: "orochi-cloud"
  JWT_ACCESS_TOKEN_TTL: "15m"
  JWT_REFRESH_TOKEN_TTL: "168h"

  # Admin user seeding
  ADMIN_EMAIL: "admin@orochi.cloud"
  ADMIN_PASSWORD: "OrochiAdmin2026!"
  ADMIN_NAME: "Orochi Admin"
